### ISSUE TITLE
homework2 建議事項

### ISSUE THREAD

**Issue by hatelove** [Frank0119/tdd-day2-homework#1]
1. 測試程式中的 expected, 不建議那樣寫，可以直接使用黑箱測試的方式去描述預期結果即可。
2. production code 如果不需要存在，就不必先寫。例如 else{} 裡面沒有東西
3. 一開始 TestClass 的 [ClassInitialized] 的內容是多的，會造成閱讀測試案例上的干擾。

**Comment by Frank0119** [comment]
謝謝建議，已修改完成。
